# Generated by Django 5.0.4 on 2024-08-18 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_tmdb_id'),
        ('recommendation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='user',
        ),
        migrations.CreateModel(
            name='RecommendedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_on', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommended Movie',
                'verbose_name_plural': 'Recommended Movies',
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.DeleteModel(
            name='MovieDetail',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
