# Generated by Django 5.0.4 on 2024-08-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='TMDB identifier for the movie.', null=True, unique=True),
        ),
    ]
